### ISSUE TITLE
moodleform_mod::add_intro_editor() is deprecated

### ISSUE THREAD

**Issue by mudrd8mz** [ndunand/moodle-mod_uniljournal#3]
I am getting the following debugging message:

Function moodleform_mod::add_intro_editor() is deprecated, use 
moodleform_mod::standard_intro_elements() instead.

You may wish to use something like this to avoid it:

```
if ($CFG->branch >= 29) {
    $this->standard_intro_elements();
} else {
    $this->add_intro_editor();
}
```

**Comment by ndunand** [comment]
Thanks for reporting.
